version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala

scala: 2.12.12

env: ADOPTOPENJDK=11

matrix:
  include:
  - env: ADOPTOPENJDK=8
    script: sbt "+test"
  - env: ADOPTOPENJDK=11
    script:
      - sbt "+test"
      - sbt ++$TRAVIS_SCALA_VERSION! "mimaReportBinaryIssues"
      - sbt ++$TRAVIS_SCALA_VERSION! "benchmark/jmh:run -i 10 -wi 3 -f1 -t1"
